dist: trusty
sudo: required
before_script: test_helpers/install_nodejs4.sh
matrix:
  include:
    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - sudo test_helpers/install_regtest.sh
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
        - nvm install 8
      env: TEST_SUITE=coverage
env:
  - TEST_SUITE=eslint
script: npm run-script $TEST_SUITE

