sudo: false
language: node_js
node_js:
  - "7"
matrix:
  include:
    - node_js: "7"
      before_script:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      env: TEST_SUITE=karma-chrome
script: npm run-script $TEST_SUITE
