sudo: required
language: node_js
node_js:
  - "7"
matrix:
  include:
    - node_js: "7"
      before_script:
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - sudo apt-get install -y gdebi
        - sudo gdebi google-chrome*.deb
        - export CHROME_BIN=google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      env: TEST_SUITE=karma-chrome
script: npm run-script $TEST_SUITE
