dist: trusty
sudo: required
before_script: test_helpers/install_nodejs4.sh
addons:
  firefox: "52.0"
matrix:
  include:
    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - sudo test_helpers/install_regtest.sh
        - rm test/bitcore.js test/build-tx.js
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
        - nvm install 8
      env: TEST_SUITE=unit TEST=discovery

script: npm run-script $TEST_SUITE

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always

